#include "firmware_header.hpp"
#include <cstdint>



// 1. Pull the dynamic size variable straight from our Linker Script
// The 'extern "C"' allows C++ to read the symbol generated by the linker.
extern "C" uint32_t _app_size;


/* 2. Define the application footer structure
   Use a compiler attribute __attribute__((section(".fw_footer"))) to tell the compiler:
  "Do not put this variable in ordinary memory. Put it directly into the .fw_footer space at the very end of the binary image."	*/

__attribute__((section(".fw_header"), used))			// 'used' ensures the compiler doesn't accidentally optimize this variable away!
const Bootloader::FirmwareHeader application_footer = {
    .magic        = Bootloader::MAGIC_NUMBER,             // 0x5A5A5A5A
    .payload_size = reinterpret_cast<uint32_t>(&_app_size), // Dynamically filled by the linker (see below comments)
    .expected_crc = 0xFFFFFFFF,                           // Placeholder for now
    .version      = 1                                     // Your app version tracking
};


/*
.payload_size is now completely automatic.
Every single time you run ninja, the linker calculates how big your code is,
puts that exact number into _app_size, and compiles it straight into your footer.
When metadata.cpp compiled, the compiler didn't know what .payload_size was, so it left an empty 4-byte placeholder slot inside the .fw_header memory block.

At the end of the linking step, once _app_size is calculated to be e.g. 20,000,
the linker automatically goes back into the binary file,
finds that placeholder slot inside .fw_header (at address 0x08008604),
and stamps the value 20,000 directly into it.

*/
